nullarbor_files:
    mlst: mlst.csv
    resistome: resistome.csv
    newick: tree.newick
    core_aln: core.aln
    reference: reference.csv
    jobinfo: jobinfo.csv

sopid:
    mlst: MMS109
    resistome: MMS118
    phylogenetics: MMS108
